# ==============================================================================
# Workflow Name : Workspace - Platform
# File Name     : ws-platform.yml
# Description   :
#   This workflow deploys the platform workspace.
#
# Author        : Vincent Huybrechts
# Created       : 2025-09-09
# Last Updated  : 2025-09-09
# Version       : 1.0.0
#
# Triggers      :
#   - [ ] push
#   - [ ] pull_request
#   - [ ] schedule
#   - [x] workflow_dispatch
#
# Environment   :
#   - OS        : ubuntu-latest
#   - Language  : bash / python
#
# Notes         :
#   -
# ==============================================================================

name: Workspace - Platform

on:
  workflow_dispatch:

jobs:
  deploy_platform:
    name: Deploy Platform
    uses: ./.github/workflows/_workspace.yaml
    with:
      workspace_file: config/workspaces/platform.yaml
      apply_infrastructure: false
    secrets:
      bitwarden_token: ${{ secrets.BITWARDEN_TOKEN }}
