apiVersion: strata.huybrechts.xyz/v1
kind: provider
meta:
  name: kamatera_eu_fr
  annotations:
    description: Kamatera cloud provider — Europe Frankfurt datacenter
  labels:
    version: "1.0.0"
  tags: [haven, kamatera, provider]
spec:
  properties:
    type: kamatera
    region: eu-fr
