apiVersion: platform.huybrechts.xyz/v1
kind: resource
meta:
  name: haven_vm_manager
  annotations:
    description: Kamatera Virtual Machine for Haven Docker Swarm manager node
  labels:
    version: 1.0.0
  tags: [haven, vm, manager]
spec:
  lifecycle: null
  properties:
    provider_type: kamatera
    resource_type: virtualmachine
    unit_cost: 5.00 # USD per month
  configuration:
    os_name: "Ubuntu"
    os_code: "24.04 64bit"
    cpu_type: "A"
    cpu_cores: 1
    ram_mb: 1024
    billing: "hourly"
  storage:
    install_path: /opt/install/haven
    disks:
      - size: 20
        label: haven-vm-manager-os
        mount: /mnt/data1
    volumes:
      - name: config
        path: /mnt/data1/etc/haven
      - name: docs
        path: /mnt/data1/var/docs/haven
      - name: data
        path: /mnt/data1/var/data/haven
      - name: logs
        path: /mnt/data1/var/logs/haven
      - name: serve
        path: /mnt/data1/var/serve
